name: "Pipeline"
trigger:
  branches:
    include:
      - main
pr:
  branches:
    include:
      - master
on:
  workflow_dispatch:

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: returntocorp/semgrep-action@v1
        with:
          config: "p/default" 