name: "Pipeline"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # ✅ TruffleHog (Secrets Scanner)
      - name: Run TruffleHog
        run: |
          pip install trufflehog
          trufflehog filesystem --directory . --only-verified --json > trufflehog-results.json
        continue-on-error: true

      - name: Upload TruffleHog Report
        uses: actions/upload-artifact@v4
        with:
          name: trufflehog-results
          path: trufflehog-results.json

     # ✅ Snyk (Dependency Scanner)
      - name: Set up Snyk
        uses: snyk/actions/setup@master

      - name: Run Snyk to check for vulnerabilities
        run: snyk test --all-projects
        working-directory: SCA/vulnerable-application
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true

      - name: Download PMD
        run: |
          curl -L -o pmd.zip https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.55.0/pmd-bin-6.55.0.zip
          unzip pmd.zip -d pmd
          mv pmd/pmd-bin-6.55.0 pmd-bin

     # ✅ PMD (Code lint, code quality)
      - name: Run PMD
        run: |
          ./pmd-bin/bin/run.sh pmd \
            -d SCA/vulnerable-application/src \
            -R category/java/bestpractices.xml \
            -f html \
            -r pmd-report.html
        continue-on-error: true

      - name: Upload PMD Report
        uses: actions/upload-artifact@v4
        with:
          name: pmd-report
          path: pmd-report.html
     # ✅ Semgrep (SAST)
      - uses: returntocorp/semgrep-action@v1
        with:
          config: "p/default"
        continue-on-error: true


