name: "Pipeline"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run PMD (Gradle)
        working-directory: SAST/vulnerable-application
        run: ./gradlew pmdMain pmdTest

      - uses: returntocorp/semgrep-action@v1
        with:
          config: "p/default"

